#!/usr/bin/env zsh
SCRIPT_DIR="$( cd "$( dirname "${(%):-%x}" )" &> /dev/null && pwd )"
source $SCRIPT_DIR/utils/install-helpers.sh
stow_action=stow_install

while getopts "hD" opt; do
  case $opt in
    h)
      echo "Usage: install-work [-h] [-D]"
      echo "-h shows this"
      echo "-D uninstalls"
      exit 0
      ;;
    D)
      read "reply?Are you sure you want to uninstall $selected? (y/N) "
      echo 
      if [[ ! $reply =~ ^[Yy]$ ]]; then
        echo "Aborting"
        exit 0
      fi
      stow_action=stow_uninstall
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="bin,nvim,oh-my-zsh,tmux,zsh"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/.dotfiles
fi
selected=$(find $DOTFILES/work/* -type d -o -type l -maxdepth 0 | fzf )
if [[ -z $selected ]]; then
  echo "Must select a work dir to install"
  exit 0
fi
selected_name="$(basename "$selected" | tr . _)"

# Install generic, universal packages
# If these folders don't exist, they will eventually be created and end up in dotfiles.
# Alternatively, I coul add something in to selectively `--no-folding` the bin directory, 
# but it was easier to do this for now
mkdir -p ~/.local/share ~/.local/state 
$stow_action $DOTFILES ~/ $STOW_FOLDERS
if [[ $? -ne 0 ]]; then
  echo "Installation of generic packages failed."
  exit 1
fi

# Install machine-specific work packages
$stow_action $DOTFILES/work ~/ $selected_name
if [[ $? -ne 0 ]]; then
  echo "Installation of work-specific packages failed."
  exit 1
fi
