#!/usr/bin/env zsh
SCRIPT_DIR="$( cd "$( dirname "${(%):-%x}" )" &> /dev/null && pwd )"
source $SCRIPT_DIR/utils/install-helpers.sh

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,git,mise,nvim,oh-my-zsh,tmux,work,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

stow_install $DOTFILES ~/ $STOW_FOLDERS
