#!/usr/bin/env zsh
SCRIPT_DIR="$( cd "$( dirname "${(%):-%x}" )" &> /dev/null && pwd )"
source $SCRIPT_DIR/utils/install-helpers.sh
stow_action=stow_install

while getopts "e:hD" opt; do
  case $opt in
    h)
      echo "Usage: install-work [-h] [-D]"
      echo "-e ENV (one of: doscar, oscar_osx)"
      echo "-h shows this"
      echo "-D uninstalls"
      exit 1
      ;;
    e)
      selected="$OPTARG"
      echo "Selected env $selected at runtime"
      ;;
    D)
      read "reply?Are you sure you want to uninstall $selected? (y/N) "
      echo
      if [[ ! $reply =~ ^[Yy]$ ]]; then
        echo "Aborting"
        exit 0
      fi
      stow_action=stow_uninstall
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/.dotfiles
fi

# If the env wasn't selected at runtime, offer a lookup
if [[ -z $selected ]]; then
  if ! command -v fzf; then
    echo "fzf not installed, try running with -e to set environment manually"
    exit 1
  fi
  selected=$(find $DOTFILES/work/* -maxdepth 0 -type d -o -type l | fzf )
fi

# Check once more because this MUST be set by now
if [[ -z $selected ]]; then
  echo "Must select a work dir to install"
  exit 1
fi
selected_name="$(basename "$selected" | tr . _)"

preinstall_script=$DOTFILES/work/$selected_name/pre-install.sh
postinstall_script=$DOTFILES/work/$selected_name/post-install.sh
if [[ -f $preinstall_script ]]; then
  zsh -c "$(preinstall_script)"
exec

STOW_FOLDERS=$(<$DOTFILES/work/$selected_name/.packages)
echo "Installing $STOW_FOLDERS"

# Install generic, universal packages
# If these folders don't exist, they will eventually be created and end up in dotfiles.
# Alternatively, I coul add something in to selectively `--no-folding` the bin directory,
# but it was easier to do this for now
mkdir -p ~/.local/share ~/.local/state
$stow_action $DOTFILES ~/ $STOW_FOLDERS
if [[ $? -ne 0 ]]; then
  echo "Installation of generic packages failed."
  exit 1
fi

# Install machine-specific work packages
$stow_action $DOTFILES/work/$selected_name ~/ stow_package
if [[ $? -ne 0 ]]; then
  echo "Installation of work-specific packages failed."
  exit 1
fi

if [[ -f $postinstall_script ]]; then
  zsh -c "$(postinstall_script)"
exec
